// $('').toggleClass('active')

function mudartemafunction(){
 	if(mudartema.click){
  $('.site-topbar').toggleClass('active')
  $('a').toggleClass('active')
  $('a.hover').toggleClass('active')
  $('h1 a:hover').toggleClass('active')
  $('h2 a:hover').toggleClass('active')
  $('h3 a:hover').toggleClass('active')
  $('h4 a:hover').toggleClass('active')
  $('h5 a:hover').toggleClass('active')
  $('.h1 a:hover').toggleClass('active')
  $('.h2 a:hover').toggleClass('active')
  $('.h3 a:hover').toggleClass('active')
  $('.h4 a:hover').toggleClass('active')
  $('.h5 a:hover').toggleClass('active')
  $('.h6 a:hover').toggleClass('active')
  $('site-topbar .home-menu a:hover i').toggleClass('active')
  $('.topbar-elements li:hover').toggleClass('active')
  $('topbar-elements li:hover span').toggleClass('active')
  $('topbar-elements li:hover i').toggleClass('active')
  $('site-header .site-branding .site-title a:hover').toggleClass('active')
  $('ft-menu a:hover').toggleClass('active')
  $('ft-menu ul li a:hover').toggleClass('active')
  $('ft-menu ul li.current-menu-item > a').toggleClass('active')
  $('#nav-toggle:hover span').toggleClass('active')
  $('#nav-toggle:hover span:before').toggleClass('active')
  $('#nav-toggle:hover span:after').toggleClass('active')
  $('#nav-toggle.nav-is-visible span:before').toggleClass('active')
  $('#nav-toggle.nav-is-visible span:after').toggleClass('active')
  $('mobile-navigation ul li a:hover').toggleClass('active')
  $('entry-category:hover').toggleClass('active')
  $('block1_list article:hover .entry-title a').toggleClass('active')
  $('block1_grid article:hover .entry-title a').toggleClass('active')
  $('block2_widget .slider-content .meta-category').toggleClass('active')
  $('entry-meta a:hover').toggleClass('active')
  $('entry-taxonomies span').toggleClass('active')
  $('entry-taxonomies .post-categories li a:hover').toggleClass('active')
  $('entry-taxonomies .post-tags li a:hover').toggleClass('active')
  $('ft-paginate a:hover').toggleClass('active')
  $('ft-paginate span.current').toggleClass('active')
  $('#comments .comment .comment-wrapper .comment-meta cite span:hover').toggleClass('active')
  $('#comments .comment .comment-wrapper .comment-meta .comment-time:hover').toggleClass('active')
  $('#comments .comment .comment-wrapper .comment-meta .comment-reply-link:hover').toggleClass('active')
  $('#comments .comment .comment-wrapper .comment-meta .comment-edit-link:hover').toggleClass('active')
  $('#comments .comment .comment-wrapper .comment-reply-login:hover').toggleClass('active')
  $('#comments .comment .comment-wrapper .comment-meta cite .fn a:hover').toggleClass('active')
  $('widget-title a').toggleClass('active')
  $('widget a:hover').toggleClass('active')
  $('widget .widget-title a').toggleClass('active')
  $('widget_categories ul li:hover .cat-count').toggleClass('active')
  $('widget.widget_recent_comments .comment-author-link a').toggleClass('active')
  $('widget.widget_recent_comments a').toggleClass('active')
  $('widget_tag_cloud a:hover').toggleClass('active')
  $('w3-red').toggleClass('active')
  $('w3-red').toggleClass('active')
  $('span').toggleClass('active')
  $('site-description').toggleClass('active')
  $('button1w').toggleClass('active')
  $('button2w').toggleClass('active')
  $('button3w').toggleClass('active')
  $('button1cw').toggleClass('active')
  $('button2cw').toggleClass('active')
  $('button3cw').toggleClass('active')
  $('.home-menu:hover.active').toggleClass('active')
  }
}






